### ISSUE TITLE
Chapter 02, Sample 02: 'Twitter Client' - an issue within `ReactiveUI.ReactiveList` is causing an exception

### ISSUE THREAD

**Issue by bawkee** [kentcb/YouIandReactiveUI#9]
I just started reading this excellent book (superb job Kent, really), as someone completely new to Reactive Extensions (I've read the primer twice and introtorx.com docs) and especially to ReactiveUI, I was a bit disenchanted by an ugly exception thrown at me while scrolling the tweets in a twitter client showcase. 

```
System.NotSupportedException
  HResult=0x80131515
  Message=Range actions are not supported.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Data.ListCollectionView.ValidateCollectionChangedEventArgs(NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at ReactiveUI.ReactiveList`1.raiseCollectionChanged(NotifyCollectionChangedEventArgs args) in C:\projects\reactiveui\src\ReactiveUI\ReactiveList.cs:line 44
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at ReactiveUI.ReactiveList`1.AddRange(IEnumerable`1 collection) in C:\projects\reactiveui\src\ReactiveUI\ReactiveList.cs:line 360
```

This happens after the 5h 'page' of tweets loaded via the scrollbar.

At this point, the reader isn't supposed to looking at the code let alone debug it, which is exactly what I did as the curiosity got the best of me :).

As it turns out, after some researching I found that the issue is already reported in reactiveui/ReactiveUI#1354 and it resulted in actual deprecation of the faulting method `ReactiveList.AddRange`. 

After doing a little bit more research I was able to find this nice page where the matter is explained in greater detail:
[ReactiveUI is deprecating ReactiveList](https://reactiveui.net/blog/2018/08/deprecated-reactive-list)

If you read that page you'll notice that a replacement is being offered, a library called DynamicData. It is an open-source library that further extends ReactiveUI offering the exact kind of real-time updates a software such as a Twitter Client would need to elegantly process new data, updates, deletions, filtering, etc. I just happen to know about this library, prior to even ordering the book, seeing as such concerns were exactly the ones I was hoping to solve with ReactiveUI so I stumbled upon it as well as this lovely book. 

Now, I believe that the original Twitter Client may work just fine with some minor fixing (i.e. not using AddRange) but at this point I'm not qualified to really give any real advice. 

Anyways, I just want to say that I'm amazed at the quality of the book (and the samples)! This was just a minor inconvenience that was too tempting for me not to open up the hood.

**Comment by kentcb** [comment]
Hi Bojan,

Thanks for the feedback. Yeah, I used reactive lists somewhat reluctantly
as I knew the move to DD was coming. However, I had to release a book
consistent with the current guidance and DD wasn't being officially
recommended as yet. I do mention it towards the end of the chapter on
reactive lists too.

Best,
Kent
